project:
  type: website
  output-dir: docs/_site
  render:
    - docs/*.qmd

website:
  title: "Controversy Across Communities on Reddit"
  navbar:
    left:
      - href: docs/index.qmd
        text: Home
      - href: docs/data-and-method.qmd
        text: Data and Methods
      - href: docs/eda.qmd
        text: EDA
      - href: docs/nlp.qmd
        text: NLP
      - href: docs/ml.qmd
        text: ML
      - href: docs/conclusion.qmd
        text: Conclusion

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true